// GENERATED by apps/maestro/scripts/build-plugin-libs.mjs — DO NOT EDIT.
// Source: apps/maestro/src/core/plugin-entries/maestro-epic.ts
// Regenerate with: pnpm --filter maestro build:plugin-libs
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/core/plugin-entries/maestro-epic.ts
var maestro_epic_exports = {};
__export(maestro_epic_exports, {
  EPICS_DIR: () => EPICS_DIR,
  acknowledgeReport: () => acknowledgeReport,
  addWorker: () => addWorker,
  createEpic: () => createEpic,
  epicDirFor: () => epicDirFor,
  epicOfTask: () => epicOfTask,
  formatEpic: () => formatEpic,
  isValidEpicSlug: () => isValidEpicSlug,
  linkTasks: () => linkTasks,
  listEpics: () => listEpics,
  readEpicState: () => readEpicState,
  removeWorker: () => removeWorker,
  setManager: () => setManager,
  showEpic: () => showEpic,
  unacknowledgedReports: () => unacknowledgedReports,
  unlinkTasks: () => unlinkTasks,
  writeReport: () => writeReport
});
module.exports = __toCommonJS(maestro_epic_exports);

// src/core/epics.ts
var import_node_fs8 = __toESM(require("node:fs"), 1);
var import_node_path6 = __toESM(require("node:path"), 1);

// src/core/worktree.ts
var import_node_fs = __toESM(require("node:fs"), 1);
var import_node_path = __toESM(require("node:path"), 1);
function mainCheckoutRoot(dir) {
  const gitEntry = import_node_path.default.join(dir, ".git");
  try {
    if (!import_node_fs.default.statSync(gitEntry).isFile()) return dir;
    const text = import_node_fs.default.readFileSync(gitEntry, "utf8");
    const m = /^gitdir:\s*(.+?)\s*$/m.exec(text);
    if (!m) return dir;
    const gitDir = import_node_path.default.resolve(dir, m[1]);
    if (import_node_path.default.basename(import_node_path.default.dirname(gitDir)) !== "worktrees") return dir;
    const common = import_node_path.default.dirname(import_node_path.default.dirname(gitDir));
    if (import_node_path.default.basename(common) !== ".git") return dir;
    return import_node_path.default.dirname(common);
  } catch {
    return dir;
  }
}

// src/core/tasks.ts
var import_node_fs7 = __toESM(require("node:fs"), 1);
var import_node_path5 = __toESM(require("node:path"), 1);

// src/core/claims.ts
var import_node_fs6 = __toESM(require("node:fs"), 1);
var import_node_path4 = __toESM(require("node:path"), 1);

// src/core/session-paths.ts
var import_node_fs2 = __toESM(require("node:fs"), 1);
var import_node_path2 = __toESM(require("node:path"), 1);
var SESSIONS_DIR_NAME = "maestro_sessions";
var SESSION_LOG_NAME = "log.jsonl";
var SESSION_STATE_NAME = "session.json";
var SESSION_TASKS_NAME = "tasks.json";
var SESSION_WORKTREE_NAME = "worktree.json";
var SESSION_ID_RE = /^[A-Za-z0-9_-]{1,128}$/;
function isValidSessionId(id) {
  return typeof id === "string" && SESSION_ID_RE.test(id);
}
function sessionsRoot(claudeDir) {
  return import_node_path2.default.join(claudeDir, SESSIONS_DIR_NAME);
}
function readWorktreePointer(claudeDir, id) {
  if (!claudeDir || !isValidSessionId(id)) return null;
  try {
    const raw = JSON.parse(
      import_node_fs2.default.readFileSync(import_node_path2.default.join(sessionsRoot(claudeDir), id, SESSION_WORKTREE_NAME), "utf8")
    );
    const p = raw;
    if (!p || typeof p.path !== "string" || !import_node_path2.default.isAbsolute(p.path)) return null;
    if (!import_node_fs2.default.statSync(p.path).isDirectory()) return null;
    return p;
  } catch {
    return null;
  }
}
function effectiveClaudeDir(claudeDir, id) {
  const pointer = readWorktreePointer(claudeDir, id);
  return pointer ? import_node_path2.default.join(pointer.path, ".claude") : claudeDir;
}
function sessionPathsFor(claudeDir, id) {
  if (!claudeDir || !isValidSessionId(id)) return null;
  const dir = import_node_path2.default.join(sessionsRoot(effectiveClaudeDir(claudeDir, id)), id);
  return {
    id,
    dir,
    log: import_node_path2.default.join(dir, SESSION_LOG_NAME),
    state: import_node_path2.default.join(dir, SESSION_STATE_NAME),
    tasks: import_node_path2.default.join(dir, SESSION_TASKS_NAME)
  };
}

// src/core/handoff-channels.ts
var import_node_fs5 = __toESM(require("node:fs"), 1);
var import_node_path3 = __toESM(require("node:path"), 1);

// src/core/session-runtime.ts
var import_node_fs4 = __toESM(require("node:fs"), 1);

// src/core/session-usage.ts
var import_node_fs3 = __toESM(require("node:fs"), 1);
var TAIL_CHUNK_BYTES = 64 * 1024;
var MAX_TAIL_BYTES = 4 * 1024 * 1024;

// src/core/handoff-channels.ts
var CHANNEL_AGE_CAP_MS = 14 * 24 * 60 * 60 * 1e3;
var CLAIM_IDLE_CAP_MS = 15 * 60 * 1e3;

// src/core/claims.ts
var CLAIMS_DIR_NAME = "claims";
function claimsDirFor(tasksDir) {
  return import_node_path4.default.join(tasksDir, CLAIMS_DIR_NAME);
}
function nameOf(claim) {
  return typeof claim.session_name === "string" && claim.session_name ? { sessionName: claim.session_name } : {};
}
function readClaimFile(filePath) {
  try {
    const data = JSON.parse(import_node_fs6.default.readFileSync(filePath, "utf8"));
    if (data && typeof data === "object" && typeof data.session_id === "string" && typeof data.claimed_at === "string") {
      return data;
    }
    return null;
  } catch {
    return null;
  }
}
function isSessionLive(claudeDir, sessionId, now2 = Date.now()) {
  const paths = sessionPathsFor(claudeDir, sessionId);
  if (!paths) return false;
  if (!import_node_fs6.default.existsSync(paths.dir)) return false;
  try {
    const stat = import_node_fs6.default.statSync(paths.log);
    return now2 - stat.mtimeMs <= CLAIM_IDLE_CAP_MS;
  } catch {
    return false;
  }
}
function listClaimFiles(dir) {
  try {
    return import_node_fs6.default.readdirSync(dir).filter((f) => f.endsWith(".json"));
  } catch {
    return [];
  }
}
function readClaims(projectRoot, tasksDir, now2 = Date.now()) {
  const claudeDir = import_node_path4.default.join(projectRoot, ".claude");
  const dir = claimsDirFor(tasksDir);
  const out = /* @__PURE__ */ new Map();
  for (const fileName of listClaimFiles(dir)) {
    const filePath = import_node_path4.default.join(dir, fileName);
    const claim = readClaimFile(filePath);
    if (!claim) continue;
    const filename = fileName.slice(0, -".json".length);
    const live = isSessionLive(claudeDir, claim.session_id, now2);
    out.set(filename, { sessionId: claim.session_id, claimedAt: claim.claimed_at, live, ...nameOf(claim) });
    if (!live) {
      try {
        import_node_fs6.default.rmSync(filePath, { force: true });
      } catch {
      }
    }
  }
  return out;
}

// src/core/tasks.ts
var TASKS_SUBDIR = import_node_path5.default.join(".claude", "maestro-tasks");
var STATUS_FILE = "status.json";
function tasksDirFor(projectRoot) {
  return import_node_path5.default.join(mainCheckoutRoot(projectRoot), TASKS_SUBDIR);
}
function parseBlockedBy(content) {
  const start = content.search(/^##\s+Blocked by\s*$/m);
  if (start === -1) return [];
  const rest = content.slice(start);
  const nextHeading = rest.slice(1).search(/^##\s/m);
  const body = nextHeading === -1 ? rest : rest.slice(0, nextHeading + 1);
  const refs = body.match(/`(\d{3}-[\w-]+\.md)`/g) ?? [];
  return Array.from(new Set(refs.map((r) => r.replace(/`/g, ""))));
}
function readStatusMap(dir) {
  try {
    const data = JSON.parse(import_node_fs7.default.readFileSync(import_node_path5.default.join(dir, STATUS_FILE), "utf8"));
    return data && typeof data === "object" ? data : {};
  } catch {
    return {};
  }
}
function writeStatusMap(dir, statusMap) {
  import_node_fs7.default.mkdirSync(dir, { recursive: true });
  const ordered = {};
  for (const k of Object.keys(statusMap).sort((a, b) => a.localeCompare(b))) {
    ordered[k] = statusMap[k];
  }
  const target = import_node_path5.default.join(dir, STATUS_FILE);
  const tmp = `${target}.${process.pid}.tmp`;
  import_node_fs7.default.writeFileSync(tmp, `${JSON.stringify(ordered, null, 2)}
`);
  import_node_fs7.default.renameSync(tmp, target);
}
function listTaskFiles(dir) {
  try {
    return import_node_fs7.default.readdirSync(dir).filter((f) => f.endsWith(".md")).sort((a, b) => a.localeCompare(b));
  } catch {
    return [];
  }
}
function readFileSafe(dir, filename) {
  try {
    return import_node_fs7.default.readFileSync(import_node_path5.default.join(dir, filename), "utf8");
  } catch {
    return "";
  }
}
function buildStatusMap(dir, files, doneSet, previous = {}) {
  const fileSet = new Set(files);
  const out = {};
  for (const filename of files) {
    const blockedBy = parseBlockedBy(readFileSafe(dir, filename));
    out[filename] = {
      status: doneSet.has(filename) ? "done" : blockedBy.every((b) => doneSet.has(b) || !fileSet.has(b)) ? "ready" : "blocked",
      blockedBy,
      // `084`: the tracker owns `epic`, the markdown never does, so a rebuild keeps what was linked.
      ...previous[filename]?.epic ? { epic: previous[filename].epic } : {}
    };
  }
  return out;
}
function setTaskEpic(projectRoot, filenames, epic) {
  const dir = tasksDirFor(projectRoot);
  const files = new Set(listTaskFiles(dir));
  const map = readStatusMap(dir);
  const changed = [];
  const missing = [];
  for (const raw of filenames) {
    const name = import_node_path5.default.basename(raw);
    if (!files.has(name)) {
      missing.push(name);
      continue;
    }
    const entry = map[name] ?? buildStatusMap(dir, [name], /* @__PURE__ */ new Set())[name];
    if (epic) entry.epic = epic;
    else delete entry.epic;
    map[name] = entry;
    changed.push(name);
  }
  if (missing.length) return { changed: [], missing };
  if (changed.length) writeStatusMap(dir, map);
  return { changed, missing };
}
function readTaskTracker(projectRoot) {
  const map = readStatusMap(tasksDirFor(projectRoot));
  const out = {};
  for (const [name, entry] of Object.entries(map)) out[name] = { status: entry?.status, epic: entry?.epic };
  return out;
}

// src/core/epics.ts
var EPICS_DIR = import_node_path6.default.join(".claude", "epics");
var EPIC_FILE = "EPIC.md";
var STATE_FILE = "state.json";
var INBOX_DIR = "inbox";
var LOCK_DIR = ".lock";
var LOCK_WAIT_MS = 5e3;
var LOCK_STALE_MS = 15e3;
var SLUG = /^[a-z0-9][a-z0-9-]{0,63}$/;
function isValidEpicSlug(slug) {
  return SLUG.test(slug);
}
function epicDirFor(projectRoot, slug) {
  if (!isValidEpicSlug(slug)) return null;
  return import_node_path6.default.join(mainCheckoutRoot(projectRoot), EPICS_DIR, slug);
}
function now() {
  return (/* @__PURE__ */ new Date()).toISOString();
}
function sleepSync(ms) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}
function withLock(dir, fn) {
  const lock = import_node_path6.default.join(dir, LOCK_DIR);
  const start = Date.now();
  for (; ; ) {
    try {
      import_node_fs8.default.mkdirSync(lock);
      break;
    } catch (err) {
      if (err.code !== "EEXIST") throw err;
      try {
        if (Date.now() - import_node_fs8.default.statSync(lock).mtimeMs > LOCK_STALE_MS) import_node_fs8.default.rmSync(lock, { recursive: true, force: true });
      } catch {
      }
      if (Date.now() - start > LOCK_WAIT_MS) throw new Error(`epic is locked by another writer (${lock})`);
      sleepSync(15);
    }
  }
  try {
    return fn();
  } finally {
    import_node_fs8.default.rmSync(lock, { recursive: true, force: true });
  }
}
function readEpicState(projectRoot, slug) {
  const dir = epicDirFor(projectRoot, slug);
  if (!dir) return null;
  try {
    const data = JSON.parse(import_node_fs8.default.readFileSync(import_node_path6.default.join(dir, STATE_FILE), "utf8"));
    if (!data || typeof data !== "object") return null;
    const s = data;
    return {
      slug,
      created_at: typeof s.created_at === "string" ? s.created_at : "",
      manager: s.manager && typeof s.manager.name === "string" ? s.manager : null,
      workers: Array.isArray(s.workers) ? s.workers : [],
      log: Array.isArray(s.log) ? s.log : []
    };
  } catch {
    return null;
  }
}
function writeEpicState(dir, state) {
  const target = import_node_path6.default.join(dir, STATE_FILE);
  const tmp = `${target}.${process.pid}.tmp`;
  import_node_fs8.default.writeFileSync(tmp, `${JSON.stringify(state, null, 2)}
`);
  import_node_fs8.default.renameSync(tmp, target);
}
function updateState(projectRoot, slug, fn) {
  const dir = epicDirFor(projectRoot, slug);
  if (!dir || !import_node_fs8.default.existsSync(import_node_path6.default.join(dir, STATE_FILE))) throw new Error(`no epic "${slug}"`);
  return withLock(dir, () => {
    const state = readEpicState(projectRoot, slug);
    if (!state) throw new Error(`epic "${slug}" has an unreadable ${STATE_FILE}`);
    const result = fn(state);
    writeEpicState(dir, state);
    return result;
  });
}
function createEpic(projectRoot, slug, options = {}) {
  const dir = epicDirFor(projectRoot, slug);
  if (!dir)
    throw new Error(
      `"${slug}" is not a valid epic name (lowercase letters, digits and dashes, starting with a letter or digit)`
    );
  if (import_node_fs8.default.existsSync(import_node_path6.default.join(dir, STATE_FILE))) throw new Error(`epic "${slug}" already exists`);
  import_node_fs8.default.mkdirSync(import_node_path6.default.join(dir, INBOX_DIR), { recursive: true });
  const goal = options.goal?.trim() || "_State the goal of this epic._";
  const epicMd = import_node_path6.default.join(dir, EPIC_FILE);
  if (!import_node_fs8.default.existsSync(epicMd)) {
    import_node_fs8.default.writeFileSync(
      epicMd,
      `# Epic: ${slug}

## Goal

${goal}

## Scope

_What is in and out of this epic._

## Decisions

_Record decisions here as the manager makes them._
`
    );
  }
  const state = {
    slug,
    created_at: now(),
    manager: options.manager ? { name: options.manager, set_at: now() } : null,
    workers: [],
    log: []
  };
  writeEpicState(dir, state);
  return { dir };
}
function listEpics(projectRoot) {
  try {
    const root = import_node_path6.default.join(mainCheckoutRoot(projectRoot), EPICS_DIR);
    return import_node_fs8.default.readdirSync(root, { withFileTypes: true }).filter((e) => e.isDirectory() && import_node_fs8.default.existsSync(import_node_path6.default.join(root, e.name, STATE_FILE))).map((e) => e.name).sort();
  } catch {
    return [];
  }
}
function setManager(projectRoot, slug, name) {
  updateState(projectRoot, slug, (s) => {
    s.manager = { name, set_at: now() };
  });
}
function addWorker(projectRoot, slug, name, task) {
  updateState(projectRoot, slug, (s) => {
    const existing = s.workers.find((w) => w.name === name);
    if (existing) {
      if (task) existing.task = task;
    } else {
      s.workers.push({ name, ...task ? { task } : {}, added_at: now() });
    }
  });
}
function removeWorker(projectRoot, slug, name) {
  updateState(projectRoot, slug, (s) => {
    s.workers = s.workers.filter((w) => w.name !== name);
  });
}
function linkTasks(projectRoot, slug, tasks) {
  if (!readEpicState(projectRoot, slug)) throw new Error(`no epic "${slug}"`);
  return setTaskEpic(projectRoot, tasks, slug);
}
function unlinkTasks(projectRoot, tasks) {
  return setTaskEpic(projectRoot, tasks, null);
}
function epicOfTask(projectRoot, filename) {
  return readTaskTracker(projectRoot)[import_node_path6.default.basename(filename)]?.epic ?? null;
}
function writeReport(projectRoot, task, body, from) {
  const base = import_node_path6.default.basename(task);
  const slug = epicOfTask(projectRoot, base);
  if (!slug) return null;
  const dir = epicDirFor(projectRoot, slug);
  if (!dir || !readEpicState(projectRoot, slug))
    throw new Error(`task "${base}" names epic "${slug}", which does not exist`);
  return updateState(projectRoot, slug, (s) => {
    const used = s.log.filter((e) => e.kind === "report").map((e) => Number(e.id.slice(1)) || 0);
    const id = `r${String((used.length ? Math.max(...used) : 0) + 1).padStart(3, "0")}`;
    const rel = import_node_path6.default.posix.join(INBOX_DIR, `${id}-${base.replace(/\.md$/, "")}.md`);
    const at = now();
    const header = `# Report ${id}: ${base}

- Task: ${base}
- Written: ${at}
${from ? `- From session: ${from}
` : ""}
`;
    import_node_fs8.default.mkdirSync(import_node_path6.default.join(dir, INBOX_DIR), { recursive: true });
    import_node_fs8.default.writeFileSync(import_node_path6.default.join(dir, rel), `${header}${body.trim()}
`);
    s.log.push({ kind: "report", id, task: base, file: rel, at, ...from ? { from } : {} });
    return { epic: slug, id, file: import_node_path6.default.join(dir, rel), manager: s.manager?.name ?? null };
  });
}
function acknowledgeReport(projectRoot, slug, id, by) {
  return updateState(projectRoot, slug, (s) => {
    if (!s.log.some((e) => e.kind === "report" && e.id === id)) throw new Error(`epic "${slug}" has no report "${id}"`);
    if (s.log.some((e) => e.kind === "ack" && e.id === id)) return "already";
    s.log.push({ kind: "ack", id, at: now(), ...by ? { by } : {} });
    return "acknowledged";
  });
}
function unacknowledgedReports(state) {
  const acked = new Set(state.log.filter((e) => e.kind === "ack").map((e) => e.id));
  return state.log.filter((e) => e.kind === "report" && !acked.has(e.id));
}
function showEpic(projectRoot, slug) {
  const state = readEpicState(projectRoot, slug);
  const dir = epicDirFor(projectRoot, slug);
  if (!state || !dir) throw new Error(`no epic "${slug}"`);
  const root = mainCheckoutRoot(projectRoot);
  const tracker = readTaskTracker(root);
  const claims = readClaims(root, tasksDirFor(root));
  const tasks = Object.keys(tracker).filter((f) => tracker[f].epic === slug).sort((a, b) => a.localeCompare(b)).map((filename) => {
    const claim = claims.get(filename);
    return {
      filename,
      status: tracker[filename].status ?? "unknown",
      running: claim?.live ? { sessionId: claim.sessionId, sessionName: claim.sessionName ?? null } : null
    };
  });
  return {
    slug,
    dir,
    goalFile: import_node_path6.default.join(dir, EPIC_FILE),
    manager: state.manager?.name ?? null,
    workers: state.workers,
    tasks,
    unacknowledged: unacknowledgedReports(state).map((r) => ({ ...r, path: import_node_path6.default.join(dir, r.file) }))
  };
}
function formatEpic(view) {
  const lines = [
    `Epic ${view.slug}`,
    `  goal file: ${view.goalFile}`,
    `  manager:   ${view.manager ?? "(none recorded)"}`,
    `  workers:   ${view.workers.length ? view.workers.map((w) => w.name).join(", ") : "(none recorded)"}`,
    `  tasks (${view.tasks.length}):`
  ];
  for (const t of view.tasks) {
    const who = t.running ? ` \u2014 running in session ${t.running.sessionName ? `"${t.running.sessionName}"` : "(unnamed)"}` : "";
    lines.push(`    ${t.filename}  [${t.status}]${who}`);
  }
  lines.push(`  unacknowledged reports (${view.unacknowledged.length}):`);
  for (const r of view.unacknowledged) lines.push(`    ${r.id}  ${r.task}  ${r.path}`);
  return lines.join("\n");
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  EPICS_DIR,
  acknowledgeReport,
  addWorker,
  createEpic,
  epicDirFor,
  epicOfTask,
  formatEpic,
  isValidEpicSlug,
  linkTasks,
  listEpics,
  readEpicState,
  removeWorker,
  setManager,
  showEpic,
  unacknowledgedReports,
  unlinkTasks,
  writeReport
});
