// GENERATED by apps/maestro/scripts/build-plugin-libs.mjs — DO NOT EDIT.
// Source: apps/maestro/src/core/plugin-entries/maestro-session.ts
// Regenerate with: pnpm --filter maestro build:plugin-libs
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/core/plugin-entries/maestro-session.ts
var maestro_session_exports = {};
__export(maestro_session_exports, {
  CHANNEL_AGE_CAP_MS: () => CHANNEL_AGE_CAP_MS,
  PRIOR_HANDOFF_SEEDS: () => PRIOR_SEEDS,
  SEED_HANDOFFS: () => SEED_HANDOFFS,
  SESSION_LOG_FILE: () => SESSION_LOG_FILE,
  agentRunsFromLog: () => agentRunsFromLog,
  appendSessionLog: () => appendSessionLog,
  bareAgentName: () => bareAgentName,
  channelDir: () => channelDir,
  collectAgentSkills: () => collectAgentSkills,
  ensureSessionRunId: () => ensureSessionRunId,
  formatStampedContent: () => formatStampedContent,
  handoffId: () => handoffId,
  handoffPairs: () => handoffPairs,
  handoffRoutes: () => handoffRoutes,
  isSeededHandoff: () => isSeededHandoff,
  isValidHandoffId: () => isValidHandoffId,
  laneFor: () => laneFor,
  nodeLabel: () => nodeLabel,
  parseStampedContent: () => parseStampedContent,
  projectOwnsHook: () => projectOwnsHook,
  readJson: () => readJson,
  readLane: () => readLane,
  readSession: () => readSession,
  readStdin: () => readStdin,
  resolveHandoff: () => resolveHandoff,
  resolveSearchList: () => resolveSearchList,
  resolveWorkflowName: () => resolveWorkflowName,
  resumeTarget: () => resumeTarget,
  retire: () => retire,
  routesFrom: () => routesFrom,
  sessionLogPath: () => sessionLogPath,
  splitHandoffId: () => splitHandoffId,
  successPathSteps: () => successPathSteps,
  sweep: () => sweep,
  workflowNodeLabels: () => workflowNodeLabels,
  writeSession: () => writeSession,
  writeStamp: () => writeStamp
});
module.exports = __toCommonJS(maestro_session_exports);

// src/core/success-path.ts
function resolveWorkflowName(cfg, explicit) {
  if (explicit) return explicit;
  const workflows = cfg?.workflows ?? [];
  return workflows[0]?.name || "default";
}
function resolveSearchList(cfg, session) {
  const workflows = cfg?.workflows ?? [];
  const activeWorkflowName = session?.workflow || null;
  const activeMatches = activeWorkflowName ? workflows.filter((w) => w.name === activeWorkflowName) : [];
  let warning = null;
  let searchList;
  if (activeWorkflowName && activeMatches.length > 0) {
    searchList = activeMatches;
  } else if (activeWorkflowName) {
    searchList = workflows;
    warning = `The active workflow "${activeWorkflowName}" (from maestro_session.json) matches no workflow in maestro.json. The skills below are unioned across all workflows and may be wrong \u2014 re-run maestro-set-session-workflow.js with a valid workflow name.`;
  } else {
    const fallbackName = resolveWorkflowName(cfg);
    const fallbackMatches = workflows.filter((w) => w.name === fallbackName);
    searchList = fallbackMatches.length > 0 ? fallbackMatches : workflows;
    if (workflows.length > 1) {
      warning = `No active workflow is set (maestro-set-session-workflow.js was not run); falling back to the "${fallbackName}" workflow. If you intended a different workflow, the orchestrator should set it before invoking subagents.`;
    }
  }
  return { searchList, warning, activeWorkflowName };
}
function bareAgentName(s) {
  return (s || "").split(":").pop() ?? "";
}
function collectAgentSkills(searchList, instances, agentType) {
  const instByName = (name) => (instances ?? []).find((i) => i.name === name);
  const wantAgent = bareAgentName(agentType);
  const loadedSet = /* @__PURE__ */ new Set();
  const referencedSet = /* @__PURE__ */ new Set();
  const matchedInstances = [];
  for (const wf of searchList ?? []) {
    for (const node of wf.nodes ?? []) {
      if (node.type !== "agent") continue;
      const inst = instByName(node.instance);
      if (!inst || bareAgentName(inst.agent) !== wantAgent) continue;
      matchedInstances.push(node.instance);
      for (const s of inst.loaded_skills ?? []) loadedSet.add(s);
      for (const s of inst.referenced_skills ?? []) referencedSet.add(s);
    }
  }
  for (const s of loadedSet) referencedSet.delete(s);
  return {
    loaded: Array.from(loadedSet),
    referenced: Array.from(referencedSet),
    matchedInstances
  };
}
function nodeLabel(id, wf, instances) {
  if (id === "main-session") return "";
  const n = (wf.nodes ?? []).find((x) => x.id === id);
  if (!n) return id;
  if (n.type === "agent") {
    const inst = (instances ?? []).find((i) => i.name === n.instance);
    return "@" + (inst?.name || n.instance || n.id);
  }
  if (n.type === "skill") return "/" + (n.skill || n.id);
  return "human review";
}
function successPathSteps(wf, instances) {
  const out = [];
  let cur = "main-session";
  const seen = /* @__PURE__ */ new Set();
  while (!seen.has(cur)) {
    seen.add(cur);
    const next = (wf.edges ?? []).find((e) => e.from === cur && e.kind === "success");
    if (!next) break;
    const label = nodeLabel(next.to, wf, instances);
    if (label) out.push(label);
    cur = next.to;
  }
  return out;
}
function workflowNodeLabels(wf, instances) {
  const labels = /* @__PURE__ */ new Set();
  for (const n of wf.nodes ?? []) {
    const l = nodeLabel(n.id, wf, instances);
    if (l) labels.add(l);
  }
  return labels;
}

// src/core/hook-arbitration.ts
var import_node_fs = __toESM(require("node:fs"), 1);
var import_node_path = __toESM(require("node:path"), 1);
function settingsRegisterScript(settings, event, script) {
  const entries = settings.hooks?.[event];
  if (!Array.isArray(entries)) return false;
  return entries.some(
    (e) => e && Array.isArray(e.hooks) && e.hooks.some((h) => h && typeof h.command === "string" && h.command.includes(script))
  );
}
function projectTwinName(scriptPath) {
  return import_node_path.default.basename(scriptPath).replace(/\.(js|cjs|sh)$/, "") + ".cjs";
}
function samePath(a, b) {
  const real = (p) => {
    try {
      return import_node_fs.default.realpathSync(import_node_path.default.resolve(p));
    } catch {
      return import_node_path.default.resolve(p);
    }
  };
  return real(a) === real(b);
}
var PROJECT_SETTINGS_FILES = ["settings.json", "settings.local.json"];
function projectOwnsHook(scriptPath, cwd, event) {
  if (!cwd || !scriptPath) return false;
  const projectScripts = import_node_path.default.join(cwd, ".claude", "scripts");
  if (samePath(import_node_path.default.dirname(scriptPath), projectScripts)) return false;
  const twin = projectTwinName(scriptPath);
  for (const file of PROJECT_SETTINGS_FILES) {
    let settings;
    try {
      const parsed = JSON.parse(import_node_fs.default.readFileSync(import_node_path.default.join(cwd, ".claude", file), "utf8"));
      if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) continue;
      settings = parsed;
    } catch {
      continue;
    }
    const events = event ? [event] : Object.keys(settings.hooks ?? {});
    if (events.some((e) => settingsRegisterScript(settings, e, twin))) return true;
  }
  return false;
}

// src/core/session-runtime.ts
var import_node_fs2 = __toESM(require("node:fs"), 1);
var import_node_path2 = __toESM(require("node:path"), 1);
var import_node_crypto = __toESM(require("node:crypto"), 1);
function readStdin() {
  return new Promise((resolve) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => data += chunk);
    process.stdin.on("end", () => resolve(data));
  });
}
function readJson(p) {
  try {
    return JSON.parse(import_node_fs2.default.readFileSync(p, "utf8"));
  } catch {
    return null;
  }
}
function readSession(p) {
  return readJson(p) ?? { workflow: null, generated_instances: [], run_id: null };
}
function writeSession(p, session) {
  const tmp = p + ".tmp";
  import_node_fs2.default.writeFileSync(tmp, JSON.stringify(session, null, 2));
  import_node_fs2.default.renameSync(tmp, p);
}
function ensureSessionRunId(p) {
  const session = readSession(p);
  if (session.run_id) return session.run_id;
  const run_id = import_node_crypto.default.randomUUID();
  writeSession(p, { ...session, run_id });
  return run_id;
}
var SESSION_LOG_FILE = "maestro_session.log.jsonl";
function sessionLogPath(claudeDir) {
  return import_node_path2.default.join(claudeDir, SESSION_LOG_FILE);
}
function appendSessionLog(claudeDir, entry) {
  import_node_fs2.default.appendFileSync(sessionLogPath(claudeDir), JSON.stringify(entry) + "\n");
}

// src/core/handoff-channels.ts
var import_node_fs3 = __toESM(require("node:fs"), 1);
var import_node_path3 = __toESM(require("node:path"), 1);
var CHANNEL_AGE_CAP_MS = 14 * 24 * 60 * 60 * 1e3;
var CHANNELS_DIR_NAME = "channels";
var CONSUMED_DIR_NAME = ".consumed";
function channelsRoot(projectDir) {
  return import_node_path3.default.join(projectDir, ".claude", CHANNELS_DIR_NAME);
}
function channelDir(projectDir, receiver) {
  return import_node_path3.default.join(channelsRoot(projectDir), receiver);
}
function consumedDir(projectDir, receiver) {
  return import_node_path3.default.join(channelsRoot(projectDir), CONSUMED_DIR_NAME, receiver);
}
function laneFor(projectDir, sender, receiver) {
  return import_node_path3.default.join(channelDir(projectDir, receiver), `${sender}.1.md`);
}
var STAMP_RE = /^<!-- maestro:run_id=([^\s>]+) -->\n/;
function formatStampedContent(body, runId) {
  return `<!-- maestro:run_id=${runId} -->
${body}`;
}
function parseStampedContent(content) {
  const m = STAMP_RE.exec(content);
  return m ? { runId: m[1], body: content.slice(m[0].length) } : { runId: null, body: content };
}
function senderOf(fileName) {
  const i = fileName.indexOf(".");
  return i === -1 ? fileName : fileName.slice(0, i);
}
function listDirs(dir) {
  try {
    return import_node_fs3.default.readdirSync(dir, { withFileTypes: true }).filter((d) => d.isDirectory() && d.name !== CONSUMED_DIR_NAME).map((d) => d.name);
  } catch {
    return [];
  }
}
function listFiles(dir) {
  try {
    return import_node_fs3.default.readdirSync(dir, { withFileTypes: true }).filter((d) => d.isFile()).map((d) => d.name);
  } catch {
    return [];
  }
}
function writeStamp(projectDir, sender, runId) {
  const stamped = [];
  for (const receiver of listDirs(channelsRoot(projectDir))) {
    const dir = channelDir(projectDir, receiver);
    for (const fileName of listFiles(dir)) {
      if (senderOf(fileName) !== sender) continue;
      const filePath = import_node_path3.default.join(dir, fileName);
      let content;
      try {
        content = import_node_fs3.default.readFileSync(filePath, "utf8");
      } catch {
        continue;
      }
      if (STAMP_RE.test(content)) continue;
      import_node_fs3.default.writeFileSync(filePath, formatStampedContent(content, runId));
      stamped.push(filePath);
    }
  }
  return stamped;
}
function readLane(projectDir, receiver, now = Date.now()) {
  const dir = channelDir(projectDir, receiver);
  const out = [];
  for (const fileName of listFiles(dir)) {
    const filePath = import_node_path3.default.join(dir, fileName);
    let stat;
    let content;
    try {
      stat = import_node_fs3.default.statSync(filePath);
      content = import_node_fs3.default.readFileSync(filePath, "utf8");
    } catch {
      continue;
    }
    const { runId, body } = parseStampedContent(content);
    out.push({ sender: senderOf(fileName), fileName, path: filePath, runId, ageMs: now - stat.mtimeMs, body });
  }
  return out;
}
function retire(projectDir, receiver, entry) {
  const dest = consumedDir(projectDir, receiver);
  import_node_fs3.default.mkdirSync(dest, { recursive: true });
  import_node_fs3.default.renameSync(entry.path, import_node_path3.default.join(dest, entry.fileName));
}
function sweep(projectDir, opts = {}) {
  const now = opts.now ?? Date.now();
  const ageCapMs = opts.ageCapMs ?? CHANNEL_AGE_CAP_MS;
  const removed = [];
  const root = channelsRoot(projectDir);
  const consumedRoot = import_node_path3.default.join(root, CONSUMED_DIR_NAME);
  for (const receiver of listDirs(consumedRoot)) {
    const dir = import_node_path3.default.join(consumedRoot, receiver);
    for (const fileName of listFiles(dir)) {
      const filePath = import_node_path3.default.join(dir, fileName);
      try {
        import_node_fs3.default.rmSync(filePath, { force: true });
        removed.push(filePath);
      } catch {
      }
    }
  }
  for (const receiver of listDirs(root)) {
    const dir = channelDir(projectDir, receiver);
    for (const fileName of listFiles(dir)) {
      const filePath = import_node_path3.default.join(dir, fileName);
      let stat;
      try {
        stat = import_node_fs3.default.statSync(filePath);
      } catch {
        continue;
      }
      if (now - stat.mtimeMs <= ageCapMs) continue;
      try {
        import_node_fs3.default.rmSync(filePath, { force: true });
        removed.push(filePath);
      } catch {
      }
    }
  }
  return { removed };
}

// src/core/handoff-routes.ts
function handoffRoutes(workflows, instances) {
  const instList = instances ?? [];
  const instByName = (name) => name === void 0 ? void 0 : instList.find((i) => i.name === name);
  const out = [];
  const seen = /* @__PURE__ */ new Set();
  for (const wf of workflows ?? []) {
    const nodes = wf.nodes ?? [];
    const edges = wf.edges ?? [];
    const nodeById = (id) => nodes.find((n) => n.id === id);
    const agentOfNode = (node, followSuccess, visited = /* @__PURE__ */ new Set()) => {
      if (!node || visited.has(node.id)) return null;
      visited.add(node.id);
      if (node.type === "agent") {
        const inst = instByName(node.instance);
        return inst ? bareAgentName(inst.agent) : null;
      }
      if (!followSuccess) return null;
      const next = edges.find((e) => e.from === node.id && e.kind === "success");
      return next ? agentOfNode(nodeById(next.to), true, visited) : null;
    };
    for (const node of nodes) {
      if (node.type !== "agent") continue;
      const inst = instByName(node.instance);
      if (!inst) continue;
      const sender = bareAgentName(inst.agent);
      for (const edge of edges) {
        if (edge.from !== node.id) continue;
        const label = edge.kind === "success" ? "success" : edge.label;
        if (!label) continue;
        const key = `${sender} ${label}`;
        if (seen.has(key)) continue;
        seen.add(key);
        out.push({ sender, receiver: agentOfNode(nodeById(edge.to), edge.kind === "success"), label });
      }
    }
  }
  return out;
}
function routesFrom(routes, agent) {
  const bare = bareAgentName(agent);
  return routes.filter((r) => r.sender === bare);
}
function handoffPairs(routes) {
  const ids = /* @__PURE__ */ new Set();
  for (const r of routes) if (r.receiver) ids.add(`${r.sender}/${r.receiver}`);
  return [...ids];
}

// src/core/handoff-seeds.ts
var BACKEND_TO_FRONTEND = '```json\n{\n  "files_added_removed_renamed": ["<list, or \'none\'>"],\n  "api_contracts": ["<endpoint \u2014 request/response shape the UI consumes>"],\n  "integration_notes": ["<how the frontend should wire it up, or \'none\'>"],\n  "edge_cases": ["<edge case the UI must handle, or \'none\'>"]\n}\n```';
var BACKEND_TO_MOBILE = '```json\n{\n  "files_added_removed_renamed": ["<list, or \'none\'>"],\n  "api_contracts": ["<endpoint \u2014 request/response shape the app consumes>"],\n  "integration_notes": ["<how the mobile app should wire it up, or \'none\'>"],\n  "edge_cases": ["<edge case the app must handle, or \'none\'>"]\n}\n```';
var BACKEND_TO_REVIEWER = '```json\n{\n  "files_added_removed_renamed": ["<list, or \'none\'>"],\n  "what_changed": ["<file:area \u2014 summary of the change>"],\n  "design_decisions": ["<decision and rationale, or \'none\'>"],\n  "areas_of_concern": ["<spot the reviewer should scrutinize, or \'none\'>"]\n}\n```';
var BACKEND_TO_TEST = '```json\n{\n  "files_added_removed_renamed": ["<list, or \'none\'>"],\n  "behaviors_to_test": ["<endpoint/function \u2014 expected behavior>"],\n  "how_to_run": ["<command to exercise the new code, or \'none\'>"],\n  "edge_cases": ["<edge case the implementation handles, or \'none\'>"]\n}\n```';
var FRONTEND_TO_MOBILE = '```json\n{\n  "files_added_removed_renamed": ["<list, or \'none\'>"],\n  "component_or_screen": "<the web feature being ported>",\n  "business_logic_to_reuse": ["<shared logic/hook/util the mobile version should reuse, or \'none\'>"],\n  "platform_differences_to_handle": ["<web-only API, layout, or interaction that needs a native equivalent, or \'none\'>"]\n}\n```';
var FRONTEND_TO_REVIEWER = '```json\n{\n  "files_added_removed_renamed": ["<list, or \'none\'>"],\n  "what_changed": ["<file:area \u2014 summary of the change>"],\n  "design_decisions": ["<decision and rationale, or \'none\'>"],\n  "areas_of_concern": ["<spot the reviewer should scrutinize, or \'none\'>"]\n}\n```';
var FRONTEND_TO_TEST = '```json\n{\n  "files_added_removed_renamed": ["<list, or \'none\'>"],\n  "behaviors_to_test": ["<component/page \u2014 expected behavior>"],\n  "how_to_run": ["<command to exercise the new UI, or \'none\'>"],\n  "edge_cases": ["<edge case the implementation handles, or \'none\'>"]\n}\n```';
var MOBILE_TO_FRONTEND = '```json\n{\n  "files_added_removed_renamed": ["<list, or \'none\'>"],\n  "component_or_screen": "<the mobile feature being ported>",\n  "business_logic_to_reuse": ["<shared logic/hook/util the web version should reuse, or \'none\'>"],\n  "platform_differences_to_handle": ["<native-only API, gesture, or interaction that needs a web equivalent, or \'none\'>"]\n}\n```';
var MOBILE_TO_REVIEWER = '```json\n{\n  "files_added_removed_renamed": ["<list, or \'none\'>"],\n  "what_changed": ["<file:area \u2014 summary of the change>"],\n  "design_decisions": ["<decision and rationale, or \'none\'>"],\n  "areas_of_concern": ["<spot the reviewer should scrutinize, or \'none\'>"]\n}\n```';
var MOBILE_TO_TEST = '```json\n{\n  "files_added_removed_renamed": ["<list, or \'none\'>"],\n  "behaviors_to_test": ["<screen/component \u2014 expected behavior>"],\n  "how_to_run": ["<command to exercise the new UI, or \'none\'>"],\n  "edge_cases": ["<edge case the implementation handles, or \'none\'>"]\n}\n```';
var REFACTOR_TO_BACKEND = '```json\n{\n  "issues": ["<file:line \u2014 description of the problem>"]\n}\n```';
var REFACTOR_TO_FRONTEND = '```json\n{\n  "issues": ["<file:line \u2014 description of the problem>"]\n}\n```';
var REFACTOR_TO_REVIEWER = '```json\n{\n  "summary": "<brief summary of what was delegated, for re-review>"\n}\n```';
var REFACTOR_TO_SCRIBE = '```json\n{\n  "new_code_patterns_or_rules": ["<pattern and which agent/rule file should receive it>"],\n  "concept_skill_gaps": [{ "skill": "<concept-skill-id>", "missing": "<what it did not tell the agent>" }]\n}\n```';
var REFACTOR_TO_TEST = '```json\n{\n  "issues": ["<file:line \u2014 description of the problem>"]\n}\n```';
var REVIEWER_TO_BACKEND = '```json\n{\n  "issues": ["<file:line \u2014 description of the problem>"]\n}\n```';
var REVIEWER_TO_FRONTEND = '```json\n{\n  "issues": ["<file:line \u2014 description of the problem>"]\n}\n```';
var REVIEWER_TO_REFACTOR = '```json\n{\n  "violations": ["<file:line \u2014 pattern violation, DRY issue, or code redundancy>"]\n}\n```';
var REVIEWER_TO_SCRIBE = `\`\`\`json
{
  "files_added_removed_renamed": ["<list, or 'none'>"],
  "justfile_commands_changed": ["<old \u2192 new description, or 'none'>"],
  "new_code_patterns_or_rules": ["<pattern and which agent/rule file should receive it, or 'none'>"],
  "schema_changes": ["<new tables, columns, or constraints, or 'none'>"],
  "workflow_or_process_changes": ["<changed agent handoff, new convention, or 'none'>"],
  "concept_skill_gaps": [{ "skill": "<concept-skill-id>", "missing": "<what it did not tell the agent>" }]
}
\`\`\``;
var REVIEWER_TO_TEST = '```json\n{\n  "failing_tests": ["<test name \u2014 failure reason>"],\n  "missing_coverage": ["<endpoint or behavior that lacks a test>"]\n}\n```';
var TEST_TO_BACKEND = '```json\n{\n  "failing_tests": ["<test name \u2014 behavior it expects>"],\n  "test_files_added": ["<list, or \'none\'>"],\n  "implementation_targets": ["<endpoint/function the backend must implement>"],\n  "how_to_run": ["<command to run the failing tests, or \'none\'>"]\n}\n```';
var TEST_TO_FRONTEND = '```json\n{\n  "failing_tests": ["<test name \u2014 behavior it expects>"],\n  "test_files_added": ["<list, or \'none\'>"],\n  "implementation_targets": ["<component/page the frontend must implement>"],\n  "how_to_run": ["<command to run the failing tests, or \'none\'>"]\n}\n```';
var TEST_TO_REVIEWER = '```json\n{\n  "tests_added": ["<test name \u2014 what it verifies>"],\n  "results": ["<pass/fail summary>"],\n  "coverage_gaps": ["<behavior still untested, or \'none\'>"],\n  "files_touched": ["<list, or \'none\'>"]\n}\n```';
var SEED_HANDOFFS = {
  "backend/frontend": BACKEND_TO_FRONTEND,
  "backend/mobile": BACKEND_TO_MOBILE,
  "backend/reviewer": BACKEND_TO_REVIEWER,
  "backend/test": BACKEND_TO_TEST,
  "frontend/mobile": FRONTEND_TO_MOBILE,
  "frontend/reviewer": FRONTEND_TO_REVIEWER,
  "frontend/test": FRONTEND_TO_TEST,
  "mobile/frontend": MOBILE_TO_FRONTEND,
  "mobile/reviewer": MOBILE_TO_REVIEWER,
  "mobile/test": MOBILE_TO_TEST,
  "refactor/backend": REFACTOR_TO_BACKEND,
  "refactor/frontend": REFACTOR_TO_FRONTEND,
  "refactor/reviewer": REFACTOR_TO_REVIEWER,
  "refactor/scribe": REFACTOR_TO_SCRIBE,
  "refactor/test": REFACTOR_TO_TEST,
  "reviewer/backend": REVIEWER_TO_BACKEND,
  "reviewer/frontend": REVIEWER_TO_FRONTEND,
  "reviewer/refactor": REVIEWER_TO_REFACTOR,
  "reviewer/scribe": REVIEWER_TO_SCRIBE,
  "reviewer/test": REVIEWER_TO_TEST,
  "test/backend": TEST_TO_BACKEND,
  "test/frontend": TEST_TO_FRONTEND,
  "test/reviewer": TEST_TO_REVIEWER
};
var PRIOR_SEEDS = {
  "backend/frontend": [
    '```json\n{\n  "handoff_details": {\n    "files_added_removed_renamed": ["<list, or \'none\'>"],\n    "api_contracts": ["<endpoint \u2014 request/response shape the UI consumes>"],\n    "integration_notes": ["<how the frontend should wire it up, or \'none\'>"],\n    "edge_cases": ["<edge case the UI must handle, or \'none\'>"]\n  }\n}\n```'
  ],
  "backend/mobile": [
    '```json\n{\n  "handoff_details": {\n    "files_added_removed_renamed": ["<list, or \'none\'>"],\n    "api_contracts": ["<endpoint \u2014 request/response shape the app consumes>"],\n    "integration_notes": ["<how the mobile app should wire it up, or \'none\'>"],\n    "edge_cases": ["<edge case the app must handle, or \'none\'>"]\n  }\n}\n```'
  ],
  "backend/reviewer": [
    '```json\n{\n  "handoff_details": {\n    "files_added_removed_renamed": ["<list, or \'none\'>"],\n    "what_changed": ["<file:area \u2014 summary of the change>"],\n    "design_decisions": ["<decision and rationale, or \'none\'>"],\n    "areas_of_concern": ["<spot the reviewer should scrutinize, or \'none\'>"]\n  }\n}\n```'
  ],
  "backend/test": [
    '```json\n{\n  "handoff_details": {\n    "files_added_removed_renamed": ["<list, or \'none\'>"],\n    "behaviors_to_test": ["<endpoint/function \u2014 expected behavior>"],\n    "how_to_run": ["<command to exercise the new code, or \'none\'>"],\n    "edge_cases": ["<edge case the implementation handles, or \'none\'>"]\n  }\n}\n```'
  ],
  "frontend/mobile": [
    '```json\n{\n  "handoff_details": {\n    "files_added_removed_renamed": ["<list, or \'none\'>"],\n    "component_or_screen": "<the web feature being ported>",\n    "business_logic_to_reuse": ["<shared logic/hook/util the mobile version should reuse, or \'none\'>"],\n    "platform_differences_to_handle": ["<web-only API, layout, or interaction that needs a native equivalent, or \'none\'>"]\n  }\n}\n```'
  ],
  "frontend/reviewer": [
    '```json\n{\n  "handoff_details": {\n    "files_added_removed_renamed": ["<list, or \'none\'>"],\n    "what_changed": ["<file:area \u2014 summary of the change>"],\n    "design_decisions": ["<decision and rationale, or \'none\'>"],\n    "areas_of_concern": ["<spot the reviewer should scrutinize, or \'none\'>"]\n  }\n}\n```'
  ],
  "frontend/test": [
    '```json\n{\n  "handoff_details": {\n    "files_added_removed_renamed": ["<list, or \'none\'>"],\n    "behaviors_to_test": ["<component/page \u2014 expected behavior>"],\n    "how_to_run": ["<command to exercise the new UI, or \'none\'>"],\n    "edge_cases": ["<edge case the implementation handles, or \'none\'>"]\n  }\n}\n```'
  ],
  "mobile/frontend": [
    '```json\n{\n  "handoff_details": {\n    "files_added_removed_renamed": ["<list, or \'none\'>"],\n    "component_or_screen": "<the mobile feature being ported>",\n    "business_logic_to_reuse": ["<shared logic/hook/util the web version should reuse, or \'none\'>"],\n    "platform_differences_to_handle": ["<native-only API, gesture, or interaction that needs a web equivalent, or \'none\'>"]\n  }\n}\n```'
  ],
  "mobile/reviewer": [
    '```json\n{\n  "handoff_details": {\n    "files_added_removed_renamed": ["<list, or \'none\'>"],\n    "what_changed": ["<file:area \u2014 summary of the change>"],\n    "design_decisions": ["<decision and rationale, or \'none\'>"],\n    "areas_of_concern": ["<spot the reviewer should scrutinize, or \'none\'>"]\n  }\n}\n```'
  ],
  "mobile/test": [
    '```json\n{\n  "handoff_details": {\n    "files_added_removed_renamed": ["<list, or \'none\'>"],\n    "behaviors_to_test": ["<screen/component \u2014 expected behavior>"],\n    "how_to_run": ["<command to exercise the new UI, or \'none\'>"],\n    "edge_cases": ["<edge case the implementation handles, or \'none\'>"]\n  }\n}\n```'
  ],
  "refactor/backend": [
    '```json\n{\n  "handoff_details": {\n    "issues": ["<file:line \u2014 description of the problem>"]\n  }\n}\n```'
  ],
  "refactor/frontend": [
    '```json\n{\n  "handoff_details": {\n    "issues": ["<file:line \u2014 description of the problem>"]\n  }\n}\n```'
  ],
  "refactor/reviewer": [
    '```json\n{\n  "handoff_details": {\n    "summary": "<brief summary of what was delegated, for re-review>"\n  }\n}\n```'
  ],
  "refactor/scribe": [
    '```json\n{\n  "handoff_details": {\n    "new_code_patterns_or_rules": ["<pattern and which agent/rule file should receive it>"],\n    "concept_skill_gaps": [{ "skill": "<concept-skill-id>", "missing": "<what it did not tell the agent>" }]\n  }\n}\n```'
  ],
  "refactor/test": [
    '```json\n{\n  "handoff_details": {\n    "issues": ["<file:line \u2014 description of the problem>"]\n  }\n}\n```'
  ],
  "reviewer/backend": [
    '```json\n{\n  "handoff_details": {\n    "issues": ["<file:line \u2014 description of the problem>"]\n  }\n}\n```'
  ],
  "reviewer/frontend": [
    '```json\n{\n  "handoff_details": {\n    "issues": ["<file:line \u2014 description of the problem>"]\n  }\n}\n```'
  ],
  "reviewer/refactor": [
    '```json\n{\n  "handoff_details": {\n    "violations": ["<file:line \u2014 pattern violation, DRY issue, or code redundancy>"]\n  }\n}\n```'
  ],
  "reviewer/scribe": [
    `\`\`\`json
{
  "handoff_details": {
    "files_added_removed_renamed": ["<list, or 'none'>"],
    "justfile_commands_changed": ["<old \u2192 new description, or 'none'>"],
    "new_code_patterns_or_rules": ["<pattern and which agent/rule file should receive it, or 'none'>"],
    "schema_changes": ["<new tables, columns, or constraints, or 'none'>"],
    "workflow_or_process_changes": ["<changed agent handoff, new convention, or 'none'>"],
    "concept_skill_gaps": [{ "skill": "<concept-skill-id>", "missing": "<what it did not tell the agent>" }]
  }
}
\`\`\``
  ],
  "reviewer/test": [
    '```json\n{\n  "handoff_details": {\n    "failing_tests": ["<test name \u2014 failure reason>"],\n    "missing_coverage": ["<endpoint or behavior that lacks a test>"]\n  }\n}\n```'
  ],
  "test/backend": [
    '```json\n{\n  "handoff_details": {\n    "failing_tests": ["<test name \u2014 behavior it expects>"],\n    "test_files_added": ["<list, or \'none\'>"],\n    "implementation_targets": ["<endpoint/function the backend must implement>"],\n    "how_to_run": ["<command to run the failing tests, or \'none\'>"]\n  }\n}\n```'
  ],
  "test/frontend": [
    '```json\n{\n  "handoff_details": {\n    "failing_tests": ["<test name \u2014 behavior it expects>"],\n    "test_files_added": ["<list, or \'none\'>"],\n    "implementation_targets": ["<component/page the frontend must implement>"],\n    "how_to_run": ["<command to run the failing tests, or \'none\'>"]\n  }\n}\n```'
  ],
  "test/reviewer": [
    '```json\n{\n  "handoff_details": {\n    "tests_added": ["<test name \u2014 what it verifies>"],\n    "results": ["<pass/fail summary>"],\n    "coverage_gaps": ["<behavior still untested, or \'none\'>"],\n    "files_touched": ["<list, or \'none\'>"]\n  }\n}\n```'
  ]
};
function isSeededHandoff(handoffId2) {
  return Object.prototype.hasOwnProperty.call(SEED_HANDOFFS, handoffId2);
}
function isValidHandoffId(handoffId2) {
  return typeof handoffId2 === "string" && /^[A-Za-z0-9_-]+\/[A-Za-z0-9_-]+$/.test(handoffId2);
}
function splitHandoffId(handoffId2) {
  if (!isValidHandoffId(handoffId2)) throw new Error(`Invalid handoff id: ${String(handoffId2)}`);
  const [sender, receiver] = handoffId2.split("/");
  return { sender, receiver };
}
function handoffId(sender, receiver) {
  return `${sender}/${receiver}`;
}

// src/core/handoff-resolution.ts
function resolveHandoff(id, projectContent, globalDefault) {
  if (projectContent) return { source: "project", content: projectContent, handoffId: id };
  if (globalDefault) return { source: "global", content: globalDefault.content, handoffId: id };
  const seed = SEED_HANDOFFS[id];
  if (seed) return { source: "seed", content: seed, handoffId: id };
  return { source: "none", content: null, handoffId: id };
}

// src/core/agent-runs.ts
function agentRunsFromLog(lines) {
  const runs = [];
  for (const line of lines ?? []) {
    if (!line || typeof line !== "object") continue;
    const entry = line;
    if (entry.kind !== "handoff") continue;
    const agentType = entry.origin;
    const agentId = entry.agent_id;
    if (typeof agentType !== "string" || !agentType) continue;
    if (typeof agentId !== "string" || !agentId) continue;
    runs.push({ agentType, agentId, ts: typeof entry.ts === "string" ? entry.ts : "" });
  }
  return runs;
}
function resumeTarget(lines, cfg, session, agentType) {
  const wantBare = bareAgentName(agentType);
  if (!wantBare) return null;
  const { searchList } = resolveSearchList(cfg, session);
  const { matchedInstances } = collectAgentSkills(searchList, cfg?.workflow_instances, agentType);
  if (new Set(matchedInstances).size > 1) return null;
  let latest = null;
  for (const run of agentRunsFromLog(lines)) {
    if (bareAgentName(run.agentType) !== wantBare) continue;
    latest = run;
  }
  return latest ? latest.agentId : null;
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  CHANNEL_AGE_CAP_MS,
  PRIOR_HANDOFF_SEEDS,
  SEED_HANDOFFS,
  SESSION_LOG_FILE,
  agentRunsFromLog,
  appendSessionLog,
  bareAgentName,
  channelDir,
  collectAgentSkills,
  ensureSessionRunId,
  formatStampedContent,
  handoffId,
  handoffPairs,
  handoffRoutes,
  isSeededHandoff,
  isValidHandoffId,
  laneFor,
  nodeLabel,
  parseStampedContent,
  projectOwnsHook,
  readJson,
  readLane,
  readSession,
  readStdin,
  resolveHandoff,
  resolveSearchList,
  resolveWorkflowName,
  resumeTarget,
  retire,
  routesFrom,
  sessionLogPath,
  splitHandoffId,
  successPathSteps,
  sweep,
  workflowNodeLabels,
  writeSession,
  writeStamp
});
