// GENERATED by apps/maestro/scripts/build-plugin-libs.mjs — DO NOT EDIT.
// Source: apps/maestro/src/core/plugin-entries/maestro-session.ts
// Regenerate with: pnpm --filter maestro build:plugin-libs
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/core/plugin-entries/maestro-session.ts
var maestro_session_exports = {};
__export(maestro_session_exports, {
  SESSION_LOG_FILE: () => SESSION_LOG_FILE,
  appendSessionLog: () => appendSessionLog,
  bareAgentName: () => bareAgentName,
  collectAgentSkills: () => collectAgentSkills,
  nodeLabel: () => nodeLabel,
  readJson: () => readJson,
  readSession: () => readSession,
  readStdin: () => readStdin,
  resolveSearchList: () => resolveSearchList,
  resolveWorkflowName: () => resolveWorkflowName,
  sessionLogPath: () => sessionLogPath,
  successPathSteps: () => successPathSteps,
  workflowNodeLabels: () => workflowNodeLabels,
  writeSession: () => writeSession
});
module.exports = __toCommonJS(maestro_session_exports);

// src/core/success-path.ts
function resolveWorkflowName(cfg, explicit) {
  if (explicit) return explicit;
  const workflows = cfg?.workflows ?? [];
  return workflows[0]?.name || "default";
}
function resolveSearchList(cfg, session) {
  const workflows = cfg?.workflows ?? [];
  const activeWorkflowName = session?.workflow || null;
  const activeMatches = activeWorkflowName ? workflows.filter((w) => w.name === activeWorkflowName) : [];
  let warning = null;
  let searchList;
  if (activeWorkflowName && activeMatches.length > 0) {
    searchList = activeMatches;
  } else if (activeWorkflowName) {
    searchList = workflows;
    warning = `The active workflow "${activeWorkflowName}" (from maestro_session.json) matches no workflow in maestro.json. The skills below are unioned across all workflows and may be wrong \u2014 re-run maestro-set-session-workflow.js with a valid workflow name.`;
  } else {
    const fallbackName = resolveWorkflowName(cfg);
    const fallbackMatches = workflows.filter((w) => w.name === fallbackName);
    searchList = fallbackMatches.length > 0 ? fallbackMatches : workflows;
    if (workflows.length > 1) {
      warning = `No active workflow is set (maestro-set-session-workflow.js was not run); falling back to the "${fallbackName}" workflow. If you intended a different workflow, the orchestrator should set it before invoking subagents.`;
    }
  }
  return { searchList, warning, activeWorkflowName };
}
function bareAgentName(s) {
  return (s || "").split(":").pop() ?? "";
}
function collectAgentSkills(searchList, instances, agentType) {
  const instByName = (name) => (instances ?? []).find((i) => i.name === name);
  const wantAgent = bareAgentName(agentType);
  const loadedSet = /* @__PURE__ */ new Set();
  const referencedSet = /* @__PURE__ */ new Set();
  const matchedInstances = [];
  for (const wf of searchList ?? []) {
    for (const node of wf.nodes ?? []) {
      if (node.type !== "agent") continue;
      const inst = instByName(node.instance);
      if (!inst || bareAgentName(inst.agent) !== wantAgent) continue;
      matchedInstances.push(node.instance);
      for (const s of inst.loaded_skills ?? []) loadedSet.add(s);
      for (const s of inst.referenced_skills ?? []) referencedSet.add(s);
    }
  }
  for (const s of loadedSet) referencedSet.delete(s);
  return {
    loaded: Array.from(loadedSet),
    referenced: Array.from(referencedSet),
    matchedInstances
  };
}
function nodeLabel(id, wf, instances) {
  if (id === "main-session") return "";
  const n = (wf.nodes ?? []).find((x) => x.id === id);
  if (!n) return id;
  if (n.type === "agent") {
    const inst = (instances ?? []).find((i) => i.name === n.instance);
    return "@" + (inst?.name || n.instance || n.id);
  }
  if (n.type === "skill") return "/" + (n.skill || n.id);
  return "human review";
}
function successPathSteps(wf, instances) {
  const out = [];
  let cur = "main-session";
  const seen = /* @__PURE__ */ new Set();
  while (!seen.has(cur)) {
    seen.add(cur);
    const next = (wf.edges ?? []).find((e) => e.from === cur && e.kind === "success");
    if (!next) break;
    const label = nodeLabel(next.to, wf, instances);
    if (label) out.push(label);
    cur = next.to;
  }
  return out;
}
function workflowNodeLabels(wf, instances) {
  const labels = /* @__PURE__ */ new Set();
  for (const n of wf.nodes ?? []) {
    const l = nodeLabel(n.id, wf, instances);
    if (l) labels.add(l);
  }
  return labels;
}

// src/core/session-runtime.ts
var import_node_fs = __toESM(require("node:fs"), 1);
var import_node_path = __toESM(require("node:path"), 1);
function readStdin() {
  return new Promise((resolve) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => data += chunk);
    process.stdin.on("end", () => resolve(data));
  });
}
function readJson(p) {
  try {
    return JSON.parse(import_node_fs.default.readFileSync(p, "utf8"));
  } catch {
    return null;
  }
}
function readSession(p) {
  return readJson(p) ?? { workflow: null, generated_instances: [] };
}
function writeSession(p, session) {
  const tmp = p + ".tmp";
  import_node_fs.default.writeFileSync(tmp, JSON.stringify(session, null, 2));
  import_node_fs.default.renameSync(tmp, p);
}
var SESSION_LOG_FILE = "maestro_session.log.jsonl";
function sessionLogPath(claudeDir) {
  return import_node_path.default.join(claudeDir, SESSION_LOG_FILE);
}
function appendSessionLog(claudeDir, entry) {
  import_node_fs.default.appendFileSync(sessionLogPath(claudeDir), JSON.stringify(entry) + "\n");
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  SESSION_LOG_FILE,
  appendSessionLog,
  bareAgentName,
  collectAgentSkills,
  nodeLabel,
  readJson,
  readSession,
  readStdin,
  resolveSearchList,
  resolveWorkflowName,
  sessionLogPath,
  successPathSteps,
  workflowNodeLabels,
  writeSession
});
