// GENERATED by apps/maestro/scripts/build-plugin-libs.mjs — DO NOT EDIT.
// Source: apps/maestro/src/core/plugin-entries/maestro-seed.ts
// Regenerate with: pnpm --filter maestro build:plugin-libs
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/core/plugin-entries/maestro-seed.ts
var maestro_seed_exports = {};
__export(maestro_seed_exports, {
  defaultV3Config: () => defaultV3Config,
  seededAgentNames: () => seededAgentNames
});
module.exports = __toCommonJS(maestro_seed_exports);

// src/core/label-layout.ts
var NODE_W = 176;
var NODE_H = 50;
var HUMAN_W = 120;
var HUMAN_H = 60;
var SKILL_CHIP_H = 25;
var MAIN_BOX = { x: 0, y: 0, w: 192, h: 38 };
var LABEL_W = 160;
var LABEL_H = 22;
var LANE_MARGIN = 12;
var NODE_SLACK_Y = 30;
var STACK_STEP = 40;
var LABEL_SLACK_Y = 10;
var STACK_TRIES = 8;
var OFFSET_GRID = 10;
function overlaps(a, b) {
  return a.x < b.x + b.w && b.x < a.x + a.w && a.y < b.y + b.h && b.y < a.y + a.h;
}
function padY(b, pad) {
  return { x: b.x, y: b.y - pad, w: b.w, h: b.h + 2 * pad };
}
function nodeBox(n, skillCount) {
  const { x, y } = n.position ?? { x: 0, y: 0 };
  if (n.type === "human_review") return { x, y, w: HUMAN_W, h: HUMAN_H };
  const skills = n.type === "agent" ? skillCount(n.instance ?? n.id) : 0;
  return { x, y, w: NODE_W, h: NODE_H + skills * SKILL_CHIP_H };
}
function handlePoint(b, side) {
  switch (side) {
    case "left":
      return { x: b.x, y: b.y + b.h / 2 };
    case "top":
      return { x: b.x + b.w / 2, y: b.y };
    case "bottom":
      return { x: b.x + b.w / 2, y: b.y + b.h };
    default:
      return { x: b.x + b.w, y: b.y + b.h / 2 };
  }
}
var CURVATURE = 0.25;
function controlOffset(distance) {
  return distance >= 0 ? 0.5 * distance : CURVATURE * 25 * Math.sqrt(-distance);
}
function control(p, side, other) {
  switch (side) {
    case "left":
      return { x: p.x - controlOffset(p.x - other.x), y: p.y };
    case "top":
      return { x: p.x, y: p.y - controlOffset(p.y - other.y) };
    case "bottom":
      return { x: p.x, y: p.y + controlOffset(other.y - p.y) };
    default:
      return { x: p.x + controlOffset(other.x - p.x), y: p.y };
  }
}
function bezierLabelAnchor(source, target, sourceHandle, targetHandle) {
  const s = handlePoint(source, sourceHandle ?? "right");
  const t = handlePoint(target, targetHandle ?? "top");
  const sc = control(s, sourceHandle ?? "right", t);
  const tc = control(t, targetHandle ?? "top", s);
  return {
    x: 0.125 * s.x + 0.375 * sc.x + 0.375 * tc.x + 0.125 * t.x,
    y: 0.125 * s.y + 0.375 * sc.y + 0.375 * tc.y + 0.125 * t.y
  };
}
function freeLanes(boxes) {
  const spans = boxes.map((b) => ({ from: b.x, to: b.x + b.w })).sort((a, b) => a.from - b.from);
  const lanes = [];
  const leftMost = spans.length > 0 ? spans[0].from : 0;
  lanes.push({
    start: leftMost - LANE_MARGIN - LABEL_W,
    end: leftMost,
    center: leftMost - LANE_MARGIN - LABEL_W / 2
  });
  let edge = spans.length > 0 ? spans[0].to : 0;
  for (const s of spans) {
    if (s.from - edge >= LABEL_W + 2 * LANE_MARGIN) {
      lanes.push({ start: edge, end: s.from, center: (edge + s.from) / 2 });
    }
    edge = Math.max(edge, s.to);
  }
  lanes.push({ start: edge, end: Infinity, center: edge + LANE_MARGIN + LABEL_W / 2 });
  return lanes;
}
function labelBox(at) {
  return { x: at.x - LABEL_W / 2, y: at.y - LABEL_H / 2, w: LABEL_W, h: LABEL_H };
}
function roundToGrid(v) {
  return Math.round(v / OFFSET_GRID) * OFFSET_GRID + 0;
}
function placeConditionLabels(workflow, skillCount = () => 0) {
  const boxes = new Map(workflow.nodes.map((n) => [n.id, nodeBox(n, skillCount)]));
  const obstacles = [MAIN_BOX, ...boxes.values()];
  const lanes = freeLanes([...boxes.values()]);
  const placed = [];
  const clear = (box) => !obstacles.some((o) => overlaps(box, padY(o, NODE_SLACK_Y))) && !placed.some((p) => overlaps(box, padY(p, LABEL_SLACK_Y)));
  const edges = workflow.edges.map((e) => {
    if (e.kind !== "condition" || !e.label) return e;
    const source = boxes.get(e.from);
    const target = boxes.get(e.to);
    if (!source || !target) return e;
    const anchor = bezierLabelAnchor(source, target, e.sourceHandle, e.targetHandle);
    if (clear(labelBox(anchor))) {
      placed.push(labelBox(anchor));
      return e;
    }
    const exitsLeft = (e.sourceHandle ?? "right") === "left";
    const sourceRight = source.x + source.w;
    const sourceLeft = source.x;
    const candidates = exitsLeft ? lanes.filter((l) => l.end <= sourceLeft) : lanes.filter((l) => l.start >= sourceRight);
    const lane = candidates.sort((a, b) => Math.abs(a.center - anchor.x) - Math.abs(b.center - anchor.x))[0] ?? (exitsLeft ? lanes[0] : lanes[lanes.length - 1]);
    let offset = { x: roundToGrid(lane.center - anchor.x), y: 0 };
    for (let i = 0; i <= STACK_TRIES; i++) {
      for (const dy of i === 0 ? [0] : [i * STACK_STEP, -i * STACK_STEP]) {
        const candidate = { x: roundToGrid(lane.center - anchor.x), y: roundToGrid(dy) };
        const box = labelBox({ x: anchor.x + candidate.x, y: anchor.y + candidate.y });
        if (clear(box)) {
          placed.push(box);
          return { ...e, label_offset: candidate };
        }
        offset = candidate;
      }
    }
    placed.push(labelBox({ x: anchor.x + offset.x, y: anchor.y + offset.y }));
    return { ...e, label_offset: offset };
  });
  return { ...workflow, edges };
}

// src/core/seed.ts
var CORE_INSTANCES = [
  { name: "test", agent: "test", loaded_skills: [], referenced_skills: [] },
  { name: "reviewer", agent: "reviewer", loaded_skills: [], referenced_skills: [] },
  { name: "refactor", agent: "refactor", loaded_skills: [], referenced_skills: [] },
  { name: "scribe", agent: "scribe", loaded_skills: [], referenced_skills: [] }
];
var succ = (from, to) => ({
  from,
  to,
  kind: "success",
  sourceHandle: "bottom",
  targetHandle: "top"
});
var cond = (from, to, label, side = "right") => ({
  from,
  to,
  kind: "condition",
  label,
  sourceHandle: side,
  targetHandle: "top"
});
function sideTracker(nodes) {
  const xById = new Map(nodes.map((n) => [n.id, n.position?.x ?? 0]));
  const sameColumnCount = /* @__PURE__ */ new Map();
  return (from, to) => {
    const a = xById.get(from) ?? 0;
    const b = xById.get(to) ?? 0;
    if (b > a) return "right";
    if (b < a) return "left";
    const n = sameColumnCount.get(from) ?? 0;
    sameColumnCount.set(from, n + 1);
    return n % 2 === 0 ? "left" : "right";
  };
}
var BASE_STEP = 140;
var PER_SKILL_STEP = 30;
function columnNodes(ids, skillCount = () => 0) {
  let y = BASE_STEP;
  return ids.map((id) => {
    const position = { x: 0, y };
    const node = id === "human_review-1" ? { id, type: "human_review", position } : { id, type: "agent", instance: id, position };
    const skills = id === "human_review-1" ? 0 : skillCount(id);
    y += BASE_STEP + skills * PER_SKILL_STEP;
    return node;
  });
}
function buildWorkflow(name, kind, impl, skillCount = () => 0) {
  const column = kind === "tdd" ? ["test", "human_review-1", ...impl, "reviewer", "scribe"] : [...impl, "human_review-1", "test", "reviewer", "scribe"];
  const colNodes = columnNodes(column, skillCount);
  const reviewerY = colNodes.find((n) => n.id === "reviewer")?.position?.y ?? BASE_STEP;
  const nodes = [
    ...colNodes,
    { id: "refactor", type: "agent", instance: "refactor", position: { x: 360, y: reviewerY } }
  ];
  const seq = ["main-session", ...column];
  const edges = [];
  for (let i = 0; i < seq.length - 1; i++) edges.push(succ(seq[i], seq[i + 1]));
  const side = sideTracker(nodes);
  const c = (from, to, label) => cond(from, to, label, side(from, to));
  const reviewerCode = [];
  const refactorCode = [];
  if (kind === "tdd") {
    reviewerCode.push(c("reviewer", "test", "FAIL: style, data layer, error handling, security, or persistence"));
    refactorCode.push(c("refactor", "test", "finding requires code changes"));
  } else if (impl.length === 1) {
    reviewerCode.push(c("reviewer", impl[0], "FAIL: style, data layer, error handling, security, or persistence"));
    refactorCode.push(c("refactor", impl[0], "finding requires code changes"));
  } else {
    for (const a of impl) {
      reviewerCode.push(
        c("reviewer", a, `FAIL: ${a} code (style, data layer, error handling, security, or persistence)`)
      );
    }
    for (const a of impl) {
      refactorCode.push(c("refactor", a, `finding requires ${a} code changes`));
    }
  }
  edges.push(
    c("reviewer", "refactor", "FAIL: code pattern violation or code redundancy"),
    c("reviewer", "test", "FAIL: a test"),
    ...reviewerCode,
    c("refactor", "scribe", "finding is a recurring pattern an agent should know going forward"),
    ...refactorCode,
    c(
      "refactor",
      "reviewer",
      "triggered by reviewer on a systemic FAIL; notify when delegation is complete so it can re-review"
    )
  );
  if (kind === "tdd") {
    edges.push(c("human_review-1", "test", "human requested test corrections"));
  } else if (impl.length === 1) {
    edges.push(c("human_review-1", impl[0], "human requested code corrections"));
  } else {
    for (const a of impl) edges.push(c("human_review-1", a, `human requested ${a} corrections`));
  }
  return placeConditionLabels({ name, nodes, edges }, skillCount);
}
function linearWorkflow(name, steps, skillCount = () => 0) {
  let y = BASE_STEP;
  const nodes = steps.map((step) => {
    const position = { x: 0, y };
    let node;
    let skills = 0;
    if (step === "human_review-1") {
      node = { id: step, type: "human_review", position };
    } else if (step.startsWith("skill:")) {
      const skill = step.slice("skill:".length);
      node = { id: skill, type: "skill", skill, position };
    } else {
      node = { id: step, type: "agent", instance: step, position };
      skills = skillCount(step);
    }
    y += BASE_STEP + skills * PER_SKILL_STEP;
    return node;
  });
  const seq = ["main-session", ...nodes.map((n) => n.id)];
  const edges = [];
  for (let i = 0; i < seq.length - 1; i++) edges.push(succ(seq[i], seq[i + 1]));
  return placeConditionLabels({ name, nodes, edges }, skillCount);
}
function buildTestsWorkflow(name, impl, skillCount = () => 0) {
  const column = ["test", "reviewer", "scribe"];
  const colNodes = columnNodes(column, skillCount);
  const reviewerY = colNodes.find((n) => n.id === "reviewer")?.position?.y ?? BASE_STEP;
  const sideNodes = [
    { id: "refactor", type: "agent", instance: "refactor", position: { x: 360, y: reviewerY } }
  ];
  let implY = reviewerY;
  for (const a of impl) {
    sideNodes.push({ id: a, type: "agent", instance: a, position: { x: 720, y: implY } });
    implY += BASE_STEP + skillCount(a) * PER_SKILL_STEP;
  }
  const nodes = [...colNodes, ...sideNodes];
  const seq = ["main-session", ...column];
  const edges = [];
  for (let i = 0; i < seq.length - 1; i++) edges.push(succ(seq[i], seq[i + 1]));
  const side = sideTracker(nodes);
  const c = (from, to, label) => cond(from, to, label, side(from, to));
  edges.push(c("reviewer", "refactor", "FAIL: a finding big enough to delegate to the refactor agent"));
  if (impl.length === 1) {
    edges.push(c("reviewer", impl[0], "FAIL: a simple code fix found while testing"));
    edges.push(c("refactor", impl[0], "finding requires code changes"));
    edges.push(c(impl[0], "test", "fix applied; re-run the tests"));
  } else {
    for (const a of impl) edges.push(c("reviewer", a, `FAIL: a simple ${a} code fix found while testing`));
    for (const a of impl) edges.push(c("refactor", a, `finding requires ${a} code changes`));
    for (const a of impl) edges.push(c(a, "test", `${a} fix applied; re-run the tests`));
  }
  return placeConditionLabels({ name, nodes, edges }, skillCount);
}
function seededAgentNames(implAgents) {
  const impl = implAgents.length > 0 ? implAgents : ["backend"];
  return Array.from(/* @__PURE__ */ new Set([...impl, "test", "reviewer", "refactor", "scribe"])).sort();
}
function defaultV3Config(implAgents, skillMap = {}) {
  const impl = implAgents.length > 0 ? implAgents : ["backend"];
  const skillsFor = (agent) => Array.from(new Set(skillMap[agent] ?? [])).filter(Boolean);
  const instances = [
    ...impl.map((a) => ({ name: a, agent: a, loaded_skills: [], referenced_skills: skillsFor(a) })),
    ...CORE_INSTANCES.map((i) => ({ ...i, referenced_skills: skillsFor(i.name) }))
  ];
  const agentsAvailable = seededAgentNames(impl);
  const skillsAvailable = Array.from(
    /* @__PURE__ */ new Set(["use-design-check", ...instances.flatMap((i) => [...i.loaded_skills, ...i.referenced_skills])])
  );
  const skillCount = (name) => skillsFor(name).length;
  return {
    version: 3,
    agents_available: agentsAvailable,
    skills_available: skillsAvailable,
    workflow_instances: instances,
    workflows: [
      buildWorkflow("default", "default", impl, skillCount),
      buildWorkflow("tdd", "tdd", impl, skillCount),
      linearWorkflow("Refactor", ["skill:use-design-check", "human_review-1", "refactor"], skillCount),
      linearWorkflow("Documentation", ["scribe"], skillCount),
      linearWorkflow("Review", ["reviewer"], skillCount),
      buildTestsWorkflow("Tests", impl, skillCount)
    ],
    rules: []
  };
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  defaultV3Config,
  seededAgentNames
});
