/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateMarketplaceRouteImport } from './routes/create-marketplace'
import { Route as CreatePluginRouteImport } from './routes/create-plugin'
import { Route as CreateSkillRouteImport } from './routes/create-skill'
import { Route as CreateSubagentRouteImport } from './routes/create-subagent'
import { Route as MaestroRouteImport } from './routes/maestro'
import { Route as MaestroTasksRouteImport } from './routes/maestro-tasks'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SessionLogRouteImport } from './routes/session-log'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as ProjectDocsIndexRouteImport } from './routes/project-docs.index'
import { Route as ProjectDocsSlugRouteImport } from './routes/project-docs.$slug'
import { Route as DocsGroupSlugRouteImport } from './routes/docs.$group.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMarketplaceRoute = CreateMarketplaceRouteImport.update({
  id: '/create-marketplace',
  path: '/create-marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePluginRoute = CreatePluginRouteImport.update({
  id: '/create-plugin',
  path: '/create-plugin',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateSkillRoute = CreateSkillRouteImport.update({
  id: '/create-skill',
  path: '/create-skill',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateSubagentRoute = CreateSubagentRouteImport.update({
  id: '/create-subagent',
  path: '/create-subagent',
  getParentRoute: () => rootRouteImport,
} as any)
const MaestroRoute = MaestroRouteImport.update({
  id: '/maestro',
  path: '/maestro',
  getParentRoute: () => rootRouteImport,
} as any)
const MaestroTasksRoute = MaestroTasksRouteImport.update({
  id: '/maestro-tasks',
  path: '/maestro-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionLogRoute = SessionLogRouteImport.update({
  id: '/session-log',
  path: '/session-log',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDocsIndexRoute = ProjectDocsIndexRouteImport.update({
  id: '/project-docs/',
  path: '/project-docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDocsSlugRoute = ProjectDocsSlugRouteImport.update({
  id: '/project-docs/$slug',
  path: '/project-docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGroupSlugRoute = DocsGroupSlugRouteImport.update({
  id: '/docs/$group/$slug',
  path: '/docs/$group/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-marketplace': typeof CreateMarketplaceRoute
  '/create-plugin': typeof CreatePluginRoute
  '/create-skill': typeof CreateSkillRoute
  '/create-subagent': typeof CreateSubagentRoute
  '/maestro': typeof MaestroRoute
  '/maestro-tasks': typeof MaestroTasksRoute
  '/rules': typeof RulesRoute
  '/session-log': typeof SessionLogRoute
  '/skills': typeof SkillsRoute
  '/tools': typeof ToolsRoute
  '/workflows': typeof WorkflowsRoute
  '/project-docs/$slug': typeof ProjectDocsSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/project-docs/': typeof ProjectDocsIndexRoute
  '/docs/$group/$slug': typeof DocsGroupSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-marketplace': typeof CreateMarketplaceRoute
  '/create-plugin': typeof CreatePluginRoute
  '/create-skill': typeof CreateSkillRoute
  '/create-subagent': typeof CreateSubagentRoute
  '/maestro': typeof MaestroRoute
  '/maestro-tasks': typeof MaestroTasksRoute
  '/rules': typeof RulesRoute
  '/session-log': typeof SessionLogRoute
  '/skills': typeof SkillsRoute
  '/tools': typeof ToolsRoute
  '/workflows': typeof WorkflowsRoute
  '/project-docs/$slug': typeof ProjectDocsSlugRoute
  '/docs': typeof DocsIndexRoute
  '/project-docs': typeof ProjectDocsIndexRoute
  '/docs/$group/$slug': typeof DocsGroupSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-marketplace': typeof CreateMarketplaceRoute
  '/create-plugin': typeof CreatePluginRoute
  '/create-skill': typeof CreateSkillRoute
  '/create-subagent': typeof CreateSubagentRoute
  '/maestro': typeof MaestroRoute
  '/maestro-tasks': typeof MaestroTasksRoute
  '/rules': typeof RulesRoute
  '/session-log': typeof SessionLogRoute
  '/skills': typeof SkillsRoute
  '/tools': typeof ToolsRoute
  '/workflows': typeof WorkflowsRoute
  '/project-docs/$slug': typeof ProjectDocsSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/project-docs/': typeof ProjectDocsIndexRoute
  '/docs/$group/$slug': typeof DocsGroupSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-marketplace'
    | '/create-plugin'
    | '/create-skill'
    | '/create-subagent'
    | '/maestro'
    | '/maestro-tasks'
    | '/rules'
    | '/session-log'
    | '/skills'
    | '/tools'
    | '/workflows'
    | '/project-docs/$slug'
    | '/docs/'
    | '/project-docs/'
    | '/docs/$group/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-marketplace'
    | '/create-plugin'
    | '/create-skill'
    | '/create-subagent'
    | '/maestro'
    | '/maestro-tasks'
    | '/rules'
    | '/session-log'
    | '/skills'
    | '/tools'
    | '/workflows'
    | '/project-docs/$slug'
    | '/docs'
    | '/project-docs'
    | '/docs/$group/$slug'
  id:
    | '__root__'
    | '/'
    | '/create-marketplace'
    | '/create-plugin'
    | '/create-skill'
    | '/create-subagent'
    | '/maestro'
    | '/maestro-tasks'
    | '/rules'
    | '/session-log'
    | '/skills'
    | '/tools'
    | '/workflows'
    | '/project-docs/$slug'
    | '/docs/'
    | '/project-docs/'
    | '/docs/$group/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateMarketplaceRoute: typeof CreateMarketplaceRoute
  CreatePluginRoute: typeof CreatePluginRoute
  CreateSkillRoute: typeof CreateSkillRoute
  CreateSubagentRoute: typeof CreateSubagentRoute
  MaestroRoute: typeof MaestroRoute
  MaestroTasksRoute: typeof MaestroTasksRoute
  RulesRoute: typeof RulesRoute
  SessionLogRoute: typeof SessionLogRoute
  SkillsRoute: typeof SkillsRoute
  ToolsRoute: typeof ToolsRoute
  WorkflowsRoute: typeof WorkflowsRoute
  ProjectDocsSlugRoute: typeof ProjectDocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ProjectDocsIndexRoute: typeof ProjectDocsIndexRoute
  DocsGroupSlugRoute: typeof DocsGroupSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-marketplace': {
      id: '/create-marketplace'
      path: '/create-marketplace'
      fullPath: '/create-marketplace'
      preLoaderRoute: typeof CreateMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-plugin': {
      id: '/create-plugin'
      path: '/create-plugin'
      fullPath: '/create-plugin'
      preLoaderRoute: typeof CreatePluginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-skill': {
      id: '/create-skill'
      path: '/create-skill'
      fullPath: '/create-skill'
      preLoaderRoute: typeof CreateSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-subagent': {
      id: '/create-subagent'
      path: '/create-subagent'
      fullPath: '/create-subagent'
      preLoaderRoute: typeof CreateSubagentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maestro': {
      id: '/maestro'
      path: '/maestro'
      fullPath: '/maestro'
      preLoaderRoute: typeof MaestroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maestro-tasks': {
      id: '/maestro-tasks'
      path: '/maestro-tasks'
      fullPath: '/maestro-tasks'
      preLoaderRoute: typeof MaestroTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-log': {
      id: '/session-log'
      path: '/session-log'
      fullPath: '/session-log'
      preLoaderRoute: typeof SessionLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-docs/': {
      id: '/project-docs/'
      path: '/project-docs'
      fullPath: '/project-docs/'
      preLoaderRoute: typeof ProjectDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-docs/$slug': {
      id: '/project-docs/$slug'
      path: '/project-docs/$slug'
      fullPath: '/project-docs/$slug'
      preLoaderRoute: typeof ProjectDocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$group/$slug': {
      id: '/docs/$group/$slug'
      path: '/docs/$group/$slug'
      fullPath: '/docs/$group/$slug'
      preLoaderRoute: typeof DocsGroupSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateMarketplaceRoute: CreateMarketplaceRoute,
  CreatePluginRoute: CreatePluginRoute,
  CreateSkillRoute: CreateSkillRoute,
  CreateSubagentRoute: CreateSubagentRoute,
  MaestroRoute: MaestroRoute,
  MaestroTasksRoute: MaestroTasksRoute,
  RulesRoute: RulesRoute,
  SessionLogRoute: SessionLogRoute,
  SkillsRoute: SkillsRoute,
  ToolsRoute: ToolsRoute,
  WorkflowsRoute: WorkflowsRoute,
  ProjectDocsSlugRoute: ProjectDocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
  ProjectDocsIndexRoute: ProjectDocsIndexRoute,
  DocsGroupSlugRoute: DocsGroupSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
